Vagrant.configure("2") do |config|
  config.vm.box = "cbumgard/nodejs"
  
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     # vb.memory = "1024"
     
     # Share current folder in order to access config file
     #config.vm.synced_folder "", "/vagrant", type: "virtualbox"

     config.vm.synced_folder "D:\\dev\\websites\\overloop-react-tech-test-master", "/workspace", type: "virtualbox"
  end
  
end