Vagrant.configure("2") do |config|
  config.vm.box = "offensive-security/kali-linux"
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     # vb.memory = "1024"
  end
end