Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"
  
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     # vb.memory = "1024"
     
     # Share current folder in order to access config file
     #config.vm.synced_folder "", "/vagrant", type: "virtualbox"

     config.vm.synced_folder "D:\\Workspace\\qatool", "/workspace", type: "virtualbox"
  end
  
  # Begin Configuring
  config.vm.define "docker" do|docker|
    # Setting up hostname
    docker.vm.hostname = "docker"
    
    # Provisioning with script.sh
    docker.vm.provision "shell" do |s|
        s.inline = "/bin/bash /vagrant/script.sh $1"
        s.args   = "/vagrant/.env"
    end
  end 
end